# Base configuration for PyTorch classifier training

# Reproducibility configuration
seed: 42
deterministic: false  # Set to true for full determinism (slower but completely reproducible)

# Data configuration
data:
  data_dir: 'data/hymenoptera_data'
  num_workers: 4

# Training configuration
training:
  batch_size: 4
  num_epochs: 3
  device: 'cuda:0'  # Will fallback to cpu if cuda not available

# Optimizer configuration
optimizer:
  lr: 0.001
  momentum: 0.9

# Learning rate scheduler configuration
scheduler:
  step_size: 7
  gamma: 0.1

# Model configuration
model:
  num_classes: 2
  model_path: 'best_model.pth'

# Data augmentation configuration
transforms:
  train:
    resize: [224, 224]
    random_horizontal_flip: true
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  val:
    resize: [224, 224]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  test:
    resize: [224, 224]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
