# Base configuration for PyTorch classifier training

# Reproducibility configuration
seed: 42
deterministic: false  # Set to true for full determinism (slower but completely reproducible)

# Data configuration
data:
  # Dataset name (used in run directory naming)
  dataset_name: 'hymenoptera'

  # Base directory: must contain raw/ (images) and splits/ (index files from splitting.py)
  data_dir: 'data/hymenoptera_data'

  # Cross-validation settings
  fold: 0                     # Which fold to use (0-indexed)

  num_workers: 4

# Training configuration
training:
  batch_size: 4
  num_epochs: 3
  device: 'cuda:0'  # Will fallback to cpu if cuda not available

# Optimizer configuration
optimizer:
  lr: 0.001
  momentum: 0.9

# Learning rate scheduler configuration
scheduler:
  step_size: 7
  gamma: 0.1

# Model configuration
model:
  # Model type: 'base' for torchvision models, 'custom' for custom architectures
  type: 'base'

  # For base models: specify any torchvision architecture
  # Options: resnet18, resnet50, vgg16, efficientnet_b0, mobilenet_v2, etc.
  architecture: 'resnet18'

  # For custom models: specify custom architecture name
  # Options: 'simple_cnn', 'tiny_net'
  custom_architecture: null

  # Number of output classes
  num_classes: 2

  # Pretrained weights: 'DEFAULT' for ImageNet weights, null for random initialization
  weights: null

  # Additional parameters for custom models
  input_size: 224  # Input image size (for custom models)
  dropout: 0.5     # Dropout probability (for custom models that support it)

  # Legacy option (deprecated but kept for compatibility)
  model_path: 'best_model.pth'

# Data augmentation configuration
transforms:
  train:
    resize: [224, 224]
    random_horizontal_flip: true
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  val:
    resize: [224, 224]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  test:
    resize: [224, 224]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
